export const GET_ERRORS = "GET_ERRORS";
export const LOADING = "LOADING";
export const NOT_LOADING = "NOT_LOADING";
export const GET_SHOPS = "GET_SHOPS";
export const GET_FEEDS= "GET_FEEDS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const CREATE_SHOP = "CREATE_SHOP";
export const CREATE_FEED = "CREATE_FEED";
export const CREATE_PRODUCT= "CREATE_PRODUCT";